on:
  workflow_dispatch: {}

jobs:

  java-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant Execute Permissions for Gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Load Maps Keys
        env:
          MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
        run: echo "MAPS_API_KEY=$MAPS_API_KEY" >> local.properties
      - name: Run Gradle Build
        run: ./gradlew build --parallel
      - name: Generate Javadocs
        run: ./gradlew createJavaDocs
      - name: Push Javadocs to Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git add app/doc
          git commit -m "Auto Generated Javadocs"
          git push
